install.packages("igraph", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("sna", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("tm", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("stringi", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("proxy", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("rgl", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("NetData", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("devtools", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("RCurl", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("sqldf", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("wordcloud", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("xml2", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages(c('mapproj','jpeg','ggmap','networktools','maps'), repos = "http://cran.cnr.berkeley.edu/", dependencies=TRUE)
install.packages("httr", repos = "http://cran.cnr.berkeley.edu/", dependencies = TRUE)
install.packages("RNeo4j")
